"""empty message

Revision ID: 1c0122891902
Revises: None
Create Date: 2016-07-18 17:17:38.919000

"""

# revision identifiers, used by Alembic.
revision = '1c0122891902'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.drop_column('password')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('password_hash')

    ### end Alembic commands ###
