"""empty message

Revision ID: 2904eab7fd1b
Revises: 1c0122891902
Create Date: 2016-07-18 22:38:46.829114

"""

# revision identifiers, used by Alembic.
revision = '2904eab7fd1b'
down_revision = '1c0122891902'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('email')

    ### end Alembic commands ###
