"""empty message

Revision ID: 42ce730bcdaa
Revises: 0a7a8753a431
Create Date: 2016-08-14 13:00:53.345851

"""

# revision identifiers, used by Alembic.
revision = '42ce730bcdaa'
down_revision = '0a7a8753a431'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('body_html')

    ### end Alembic commands ###
