"""empty message

Revision ID: 901a33ca8fc9
Revises: 758f5c19cbfe
Create Date: 2016-08-07 19:48:02.835144

"""

# revision identifiers, used by Alembic.
revision = '901a33ca8fc9'
down_revision = '758f5c19cbfe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('lacation', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('member_since', sa.DateTime(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('member_since')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('lacation')
        batch_op.drop_column('about_me')

    ### end Alembic commands ###
