"""empty message

Revision ID: 9d72e5015d4e
Revises: 901a33ca8fc9
Create Date: 2016-08-07 20:43:34.127659

"""

# revision identifiers, used by Alembic.
revision = '9d72e5015d4e'
down_revision = '901a33ca8fc9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    ### end Alembic commands ###
