"""empty message

Revision ID: d7ebe39c3b8b
Revises: 9d72e5015d4e
Create Date: 2016-08-07 20:45:54.588962

"""

# revision identifiers, used by Alembic.
revision = 'd7ebe39c3b8b'
down_revision = '9d72e5015d4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=64), nullable=True))
        batch_op.drop_column('lacation')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lacation', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('location')

    ### end Alembic commands ###
