"""empty message

Revision ID: de8425167d0f
Revises: 2904eab7fd1b
Create Date: 2016-07-21 16:42:10.338000

"""

# revision identifiers, used by Alembic.
revision = 'de8425167d0f'
down_revision = '2904eab7fd1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    ### end Alembic commands ###
